sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: RHWROkpq7DAMhVhtG7YF+hvJjEjBkRnxrDeHHyF0In0/HM9aXC3ux3oetHMvxjiSnDWeG5cJN1HpP1zrgufdMMyAQoPJw8FaqvrAQXaJXth+YZ5smljOGdowyN/u1P8L4UTqgtQ6fkQHk3b26FyoIb+SjHrkF3fU77sRICfAvRZFHtoeD0n/igeukgK0DbksEmd1z2RJfVE74FhJ+2FvxOsq+x/M032i+wSCrbttjfeGX/HN6LB3ELYf+c5A4kwnvHUWLkQK9kkqEhqaAuBf6S88yNPvnGstLpFYIsgROIxk4YPapZtEV5FBpnDzGkKF6b7OuT/ZTMj8DMoqCzkc4qx5tmxjUAJCrcVotDneJRXoOMFffLEZJI+cakYe2x+lfnGsGZWphBwMq69MX1U7VMnspVxNTHX+jFfEEPgRaLVjGZsK+qEoJ13U0w4/u4H3fMVJfcW3kMpOO50GuQA1piP1dNPJ3yLpEEP01QNeKoqI1GWNU1zTjo3DwKiXZa08RWR1JRJyVE5fOiFtuqesszq8GlIsI+g4c3U3KnxWGBcukLGijQcFOCaEjWaY2oJOxsFzPsHL/5AM9XCQrsQl5MH1HaC/dtcjxZBO9hRfdbNJ1Ue8QkjaOaSmcZ4r0ZWDaFkR9Bu7heYJnSUXtHywwaf+CaQB4Y8Eg1maTCOu9vM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Selections-from-the-Principles-of-Philosophy_4391
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy